# Priors
[C]
prior = "Parameterized(Normal(0.833733833333333, 0.0457277258640419))"
constraint = "no_constraint()"

[dropoff]
prior = "Parameterized(Normal(16.4265, 6.1592))"
constraint = "no_constraint()"

[A]
prior = "Parameterized(Normal(0.103459, 0.003860))"
constraint = "no_constraint()"
